import Wrapper from "@/components/Wrapper/Wrapper";
import Footer from "@/components/layout/Footer";
import Navbar from "@/components/layout/Navbar";
import type { Metadata } from "next";
import { Syne } from "next/font/google";
import Script from "next/script";
import NextTopLoader from "nextjs-toploader";
import "./globals.css";
const syne = Syne({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Coderlink",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={syne.className}>
        <NextTopLoader color="#3f00ff" />
        <Wrapper>
          <Navbar />
          {children}
          <Footer />
        </Wrapper>
        <Script
          src="https://res.cloudinary.com/rohanphulkar/raw/upload/v1673963494/synfert/preline_norz6c.js"
          type="module"
        />
      </body>
    </html>
  );
}
